import { useEffect } from 'react'

export default function ApplicationModal({ packet, onClose }) {
  useEffect(() => {
    const escape = event => event.key === 'Escape' && onClose()
    document.addEventListener('keydown', escape)
    return () => document.removeEventListener('keydown', escape)
  }, [onClose])

  if (!packet) return null
  return (
    <div className="modal-layer" role="dialog" aria-modal="true" aria-labelledby="packet-title">
      <button className="modal-backdrop" onClick={onClose} aria-label="Close application preview" />
      <section className="packet-modal">
        <header className="packet-toolbar">
          <div><span>Generated application packet</span><strong>{packet.documentNumber}</strong></div>
          <div className="d-flex gap-2">
            <button className="btn btn-light btn-sm" onClick={() => window.print()}><i className="bi bi-printer me-2" />Print</button>
            <button className="icon-button" onClick={onClose} aria-label="Close"><i className="bi bi-x-lg" /></button>
          </div>
        </header>
        <article className="application-paper">
          <div className="paper-seal">NP</div>
          <p className="paper-kicker">Liberty Reckoner · Verified workflow draft</p>
          <h2 id="packet-title">{packet.heading}</h2>
          <div className="paper-meta"><span>To</span><strong>{packet.recipient}</strong></div>
          <div className="paper-meta"><span>Subject</span><strong>{packet.subject}</strong></div>
          <h3>Verified record summary</h3>
          <ol>{packet.verifiedFacts.map(fact => <li key={fact}>{fact}</li>)}</ol>
          <p className="paper-body">{packet.body}</p>
          <div className="verification-box"><i className="bi bi-patch-check-fill" /><span>{packet.verificationStatement}</span></div>
          <div className="signature-grid"><div><span>Jail Superintendent</span><strong>Digital signature required</strong></div><div><span>Generated by</span><strong>{packet.generatedBy}</strong></div></div>
        </article>
      </section>
    </div>
  )
}

